name: trybapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore:
  cupertino_icons:
  device_info:
  firebase_analytics:
  firebase_auth:
  firebase_core:
  firebase_messaging:
  flutter_facebook_login:
  flutter_svg:
  font_awesome_flutter:
  google_sign_in:
  intl:
  modal_progress_hud:
  permission_handler:
  rxdart:
  shared_preferences:
  url_launcher:
    
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
